### ISSUE TITLE
Wrong notification about unpredicted matches

### ISSUE THREAD

**Issue by IngoAlbers** [lxxxvi/maradona#124]
Actual behaviour: In my personal locker I see the message: "You have 1 unpredicted match"
When I click on "Predict them now" I see no match that needs to be predicted.

Expected behaviour: In my personal locker I don't see a message about unpredicted matches.

How to reproduce: Get invited too late to the tippkick.club after the opening game already finished.

**Comment by lxxxvi** [comment]
@IngoAlbers Thank you, I'll try to fix that.

**Comment by lxxxvi** [comment]
@IngoAlbers It should be fixed now, can you confirm that?

**Comment by IngoAlbers** [comment]
@lxxxvi  confirmed! Thank you for the quick fix.
